version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videodb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql

  authentication_service:
    build: ./auth
    ports:
      - "3001:3001"
  file-system-service:
    build: ./file-system-service
    ports:
      - "3003:3003"
    env_file:
      - ./file-system-service/.env
  video_upload_service:
    build: ./upload_service
    ports:
      - "3002:3002"
    env_file:
      - ./upload_service/.env

  video_streaming_service:
    build: ./video-streaming-app
    ports:
      - "3000:80"


volumes:
  db_data: